### ISSUE TITLE
Multiple Key

### ISSUE THREAD

**Issue by caglaraltuntass** [joncoop/zipgrade-reporter#2]
Hi. I created an exam on Zipgrade with two key labels. When I download the full .csv format, it says "something went wrong,be sure your csv data file is valid". What can I do in this case  ? Thanks in advance.

**Comment by joncoop** [comment]
Right now, it can't handle commas in the class name or test name. See if
that's the problem.

**Comment by caglaraltuntass** [comment]
[Sample.csv](https://github.com/joncoop/zipgrade-reporter/files/9667387/Sample.csv)

I attached the csv file. Can you please check it ?
